source_set("cpc_permissions") {
  sources = [
    "container_permission_snapshot.cc",
    "container_permission_snapshot.h",
    "container_permission_snapshot_serializer.cc",
    "container_permission_snapshot_serializer.h",
    "container_permission_store.cc",
    "container_permission_store.h",
  ]
  deps = [ "//base" ]
}
